"""Structural checks on supabase/migrations/20260913120000_illustration_
corpus_layer.sql -- same pragmatic "source-string assertion" convention
this repo already uses for things that cannot be executed in this
environment (no real Postgres/Supabase project reachable here; see
tests/test_illustration_retrieval_ui_cooldown.py's own docstring for the
precedent). This does NOT prove the SQL is valid Postgres -- it pins the
architectural decisions from the 2026-09-13 revised plan so a future
edit cannot silently drop one of them: which tables exist, which two are
deliberately excluded, the PK strategy, RLS-enabled-with-no-policies on
every table, the tag review-protection trigger, and the production RPC's
exact grant shape."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DDL_PATH = ROOT / "supabase" / "migrations" / "20260913120000_illustration_corpus_layer.sql"
DDL_SQL = DDL_PATH.read_text(encoding="utf-8")

EXPECTED_TABLES = (
    "illustration_sources",
    "illustration_stories",
    "illustration_units",
    "illustration_tags",
    "illustration_unit_tags",
    "illustration_qa_repairs",
    "illustration_import_meta",
    "illustration_enrichment_runs",
    "illustration_enrichment_run_items",
)


def test_migration_file_exists() -> None:
    assert DDL_PATH.is_file()


def test_all_nine_tables_created() -> None:
    for table in EXPECTED_TABLES:
        assert f"create table if not exists {table}" in DDL_SQL, f"missing table: {table}"


def test_story_tags_and_fts_deliberately_not_migrated() -> None:
    assert "create table if not exists story_tags" not in DDL_SQL
    assert "create table if not exists illustration_units_fts" not in DDL_SQL
    assert "create virtual table" not in DDL_SQL.lower()


# Tables with an integer surrogate primary key -- excludes
# illustration_unit_tags (composite PK, no own id, matches SQLite) and
# illustration_import_meta (natural `key text primary key`, matches
# SQLite's own `import_meta(key TEXT PRIMARY KEY)`).
TABLES_WITH_IDENTITY_PK = (
    "illustration_sources",
    "illustration_stories",
    "illustration_units",
    "illustration_tags",
    "illustration_qa_repairs",
    "illustration_enrichment_runs",
    "illustration_enrichment_run_items",
)


def test_primary_key_strategy_preserves_original_ids() -> None:
    """generated BY DEFAULT (not ALWAYS) as identity -- lets the migration
    script insert the original SQLite integer ids explicitly, with no
    id-remapping table needed. Junction/key-value tables (illustration_
    unit_tags, illustration_import_meta) deliberately keep their SQLite-
    matching non-identity primary keys instead."""
    occurrences = DDL_SQL.count("generated by default as identity")
    assert occurrences == len(TABLES_WITH_IDENTITY_PK), (
        f"expected {len(TABLES_WITH_IDENTITY_PK)} tables to use "
        f"'generated by default as identity', found {occurrences} occurrences"
    )
    assert "generated always as identity" not in DDL_SQL


def test_review_metadata_columns_present_on_units() -> None:
    assert "human_reviewed_at timestamptz" in DDL_SQL
    assert "reviewed_by uuid references auth.users(id)" in DDL_SQL
    assert "reviewed_by_email text" in DDL_SQL


def test_rls_enabled_on_every_table_with_no_policies() -> None:
    """RLS is enabled via a dynamic `execute format(...)` loop (see
    test_service_role_has_explicit_base_table_grants), not one literal
    `alter table ... enable row level security` statement per table --
    this checks every table name is actually listed inside that loop's
    array."""
    rls_loop_start = DDL_SQL.index("execute format('alter table %I enable row level security")
    rls_loop_block = DDL_SQL[max(0, rls_loop_start - 700) : rls_loop_start]
    for table in EXPECTED_TABLES:
        assert f"'{table}'" in rls_loop_block, f"{table} missing from the RLS-enable loop's table array"
    # Deny-by-default: no `create policy` anywhere for anon/authenticated --
    # the only sanctioned public surface is the RPC at the bottom.
    assert "create policy" not in DDL_SQL.lower()


def test_service_role_has_explicit_base_table_grants() -> None:
    """Real-PostgreSQL validation finding (2026-09-13): service_role does
    NOT automatically receive base table privileges just by existing --
    the local disposable-Postgres test caught "permission denied for
    table illustration_units" when the review-write repository's
    service_role client tried to UPDATE, because this migration
    initially omitted the explicit grant every OTHER migration in this
    repo already includes (see 20260908190000_hebrew_linguistic_layer.sql
    and 20260911220000_greek_linguistic_layer.sql's own `grant select,
    insert, update, delete on %I to service_role` loops). Pins the fix so
    it can never silently regress."""
    assert "grant select, insert, update, delete on %I to service_role" in DDL_SQL
    assert "revoke all on %I from anon, authenticated" in DDL_SQL


def test_content_completeness_and_license_gates_present() -> None:
    assert "trg_illustration_stories_publish_license_gate" in DDL_SQL
    assert "trg_illustration_units_publish_license_gate" in DDL_SQL
    assert "status != 'published'" in DDL_SQL
    assert "human_reviewed_at is not null" in DDL_SQL  # part of the units publish CHECK


def test_human_reviewed_content_protection_trigger_present() -> None:
    assert "trg_illustration_units_protect_reviewed_content" in DDL_SQL
    assert "review_gate: reviewed content can only change" in DDL_SQL


def test_tag_review_protection_extends_to_taxonomy() -> None:
    """The audit-fix requirement: taxonomy edits on an already-reviewed
    unit must be blocked at the DB layer too, not just in Python."""
    assert "trg_illustration_unit_tags_protect_reviewed" in DDL_SQL
    assert "before insert or delete on illustration_unit_tags" in DDL_SQL
    assert "call send_back_for_rework first" in DDL_SQL


def test_production_rpc_is_security_definer_with_narrow_grants() -> None:
    assert "create or replace function get_published_illustration_candidates" in DDL_SQL
    assert "security definer" in DDL_SQL
    assert "set search_path = public" in DDL_SQL
    assert "grant execute on function get_published_illustration_candidates() to anon, authenticated" in DDL_SQL


def test_production_rpc_rechecks_license_and_status_itself() -> None:
    """Never trust the publish-time trigger alone -- the RPC re-derives
    the exact same filter on every call (2026-09-13 architecture
    decision: a source retroactively marked restricted must immediately
    stop surfacing its previously-published units)."""
    rpc_start = DDL_SQL.index("create or replace function get_published_illustration_candidates")
    rpc_body = DDL_SQL[rpc_start:]
    assert "u.status = 'published'" in rpc_body
    assert "s.license_status in (" in rpc_body


def test_production_rpc_never_exposes_admin_or_reviewer_fields() -> None:
    rpc_start = DDL_SQL.index("create or replace function get_published_illustration_candidates")
    rpc_end = DDL_SQL.index("$$;", rpc_start)
    rpc_body = DDL_SQL[rpc_start:rpc_end]
    for forbidden in ("qa_issues", "qa_confidence", "enrichment_model", "enrichment_warnings", "reviewed_by"):
        assert forbidden not in rpc_body, f"production RPC must never select {forbidden}"


def test_sequence_reset_rpc_is_service_role_only() -> None:
    assert "create or replace function reset_illustration_sequences" in DDL_SQL
    assert (
        "revoke all on function reset_illustration_sequences() from public, anon, authenticated"
        in DDL_SQL
    )
    assert "grant execute on function reset_illustration_sequences() to service_role" in DDL_SQL


def test_server_trust_auth_model_documented_not_rls_user_auth() -> None:
    """Pins the auth-model correction: this migration's header must
    explicitly say server-trust, and no `create policy`/RPC in this file
    may actually GATE anything on `auth.uid()` (the header note is
    allowed to mention it explanatorily -- to say why it is NOT used)."""
    assert "SERVER-TRUST" in DDL_SQL
    assert "service_role bypasses" in DDL_SQL.lower() or "service_role` bypasses" in DDL_SQL
    # No policy anywhere (already asserted above) means auth.uid() cannot
    # be gating any RLS policy; and the RPC body itself never references it.
    rpc_start = DDL_SQL.index("create or replace function get_published_illustration_candidates")
    rpc_end = DDL_SQL.index("$$;", rpc_start)
    assert "auth.uid()" not in DDL_SQL[rpc_start:rpc_end]
