"""Phase 2A §11 — the 15 audit-selected NT regression verses, formalized as
static developer fixtures. NOT expert goldens (see the "reviewed": false
marker required on every record) — generated by
scripts/export_greek_regression_fixtures.py from the same deterministic
GreekAnalysisBundle builder tested in test_greek_analysis_bundle.py.
"""

from __future__ import annotations

import json
from pathlib import Path

FIXTURE_PATH = (
    Path(__file__).parent / "fixtures" / "greek_analysis_v2_regression_verses.json"
)


def _load() -> dict:
    return json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))


def test_fixture_file_exists_and_parses() -> None:
    data = _load()
    assert "verses" in data
    assert isinstance(data["verses"], list)


def test_fixture_contains_at_least_ten_representative_verses() -> None:
    data = _load()
    assert len(data["verses"]) >= 10


def test_every_fixture_verse_is_explicitly_marked_unreviewed() -> None:
    """Task requirement: 'these are developer fixtures, NOT expert
    goldens' — 'clearly mark them as unreviewed'."""
    data = _load()
    for record in data["verses"]:
        assert record["reviewed"] is False
        assert "review_note" in record and record["review_note"]


def test_every_fixture_verse_names_its_phenomenon() -> None:
    data = _load()
    for record in data["verses"]:
        assert record["phenomenon"].strip()


def test_fixture_covers_the_phenomena_the_phase_brief_requires() -> None:
    data = _load()
    phenomena_text = " ".join(record["phenomenon"].lower() for record in data["verses"])
    for required in (
        "aorist", "imperfect", "perfect", "middle", "participle", "infinitive",
        "genitive absolute", "conditional", "ἵνα", "article", "preposition + case",
        "difficult",
    ):
        assert required in phenomena_text, f"missing phenomenon: {required}"


def test_fixture_verses_have_ordered_non_empty_token_lists() -> None:
    data = _load()
    for record in data["verses"]:
        for verse in record["bundle"]["verses"]:
            tokens = verse["tokens"]
            assert tokens, f"{record['reference']} has an empty verse"
            indexes = [token["word_index"] for token in tokens]
            assert indexes == sorted(indexes)
