"""One-time, idempotent SQLite -> Supabase migration for the illustration
corpus (Phase 1, 2026-09-13).

Ports every row from the local `illustrations.sqlite3` (schema v6) into
the Supabase tables created by `supabase/migrations/
20260913120000_illustration_corpus_layer.sql`. Preserves every original
SQLite integer id verbatim (the DDL's `generated by default as identity`
strategy makes this possible -- no id-remapping table needed anywhere in
this script).

SAFETY:
- The source SQLite connection is ALWAYS opened `mode=ro` (URI read-only)
  -- this script cannot write to the source database even if it tried.
- `--dry-run` is the DEFAULT. It reads the source, runs every readiness
  check, prints a report ending in `READY_FOR_APPLY=true|false`, and
  exits WITHOUT touching Supabase at all (no network call is even made).
- `--apply` is required, explicitly, to write anything. It still refuses
  to run if any readiness check failed.
- Every write is an upsert against each table's natural unique
  constraint -- re-running `--apply` after a partial failure is safe and
  produces the same end state, never a duplicate row.
- This script NEVER deletes anything, in Supabase or in the source
  SQLite file.

USAGE:
    python scripts/migrate_illustrations_to_supabase.py --source PATH          # dry-run (default)
    python scripts/migrate_illustrations_to_supabase.py --source PATH --apply  # real write

This script has NOT been run in --apply mode against any real Supabase
project as of this commit -- see the Phase 1 report for what still needs
independent review first (SAFE TO RUN MIGRATION --apply: NO until the
generated DDL and a dry-run report have been reviewed).
"""

from __future__ import annotations

import argparse
import hashlib
import sqlite3
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path

DEFAULT_BATCH_SIZE = 200
DEFAULT_RETRY_ATTEMPTS = 5
DEFAULT_RETRY_BASE_DELAY = 0.5

PUBLISHABLE_LICENSE_STATUSES = frozenset(
    {"public_domain_confirmed", "public_domain_assumed_by_age", "permission_granted"}
)
ALLOWED_STORY_STATUSES = frozenset({"draft", "needs_review", "approved", "published"})
ALLOWED_UNIT_STATUSES = ALLOWED_STORY_STATUSES
ALLOWED_DERIVATION_TYPES = frozenset(
    {"full_story_translation", "condensed_story", "extracted_scene"}
)
ALLOWED_ADAPTATION_STATUSES = frozenset(
    {"verbatim_transcription", "modernized_spelling", "editorial_paraphrase"}
)
ALLOWED_NARRATIVE_STATUSES = frozenset(
    {
        "documented_historical_event", "legend_about_historical_figure", "traditional_anecdote",
        "fable", "folktale", "rabbinic_aggadic_tale", "didactic_tale",
    }
)
ALLOWED_QA_STATUSES = frozenset({"pending", "passed", "needs_attention", "failed"})
ALLOWED_TAG_CATEGORIES = frozenset({"topic", "tone", "function"})

# Migration order matters -- FK-dependency order, parents before children.
SOURCE_TABLES = (
    "sources", "stories", "illustration_units", "tags", "illustration_unit_tags",
    "qa_repairs", "import_meta", "enrichment_runs", "enrichment_run_items",
)


# ---------------------------------------------------------------------------
# Readiness checks (dry-run — no network access, pure SQLite reads)
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class CheckResult:
    name: str
    passed: bool
    detail: str = ""


@dataclass
class MigrationReadinessReport:
    source_path: Path
    row_counts: dict[str, int]
    checks: list[CheckResult] = field(default_factory=list)

    @property
    def ready_for_apply(self) -> bool:
        return bool(self.checks) and all(c.passed for c in self.checks)

    def render(self) -> str:
        lines = [f"=== Illustration migration readiness report: {self.source_path} ==="]
        lines.append(f"Row counts: {self.row_counts}")
        lines.append("")
        for c in self.checks:
            status = "PASS" if c.passed else "FAIL"
            lines.append(f"[{status}] {c.name}" + (f" -- {c.detail}" if c.detail else ""))
        lines.append("")
        lines.append(f"READY_FOR_APPLY={'true' if self.ready_for_apply else 'false'}")
        return "\n".join(lines)


def open_source_readonly(path: Path) -> sqlite3.Connection:
    """Always mode=ro -- this connection structurally cannot write,
    regardless of what the rest of this script does or any bug in it."""
    if not path.exists():
        raise FileNotFoundError(f"source SQLite DB not found: {path}")
    conn = sqlite3.connect(path.as_uri() + "?mode=ro", uri=True)
    conn.row_factory = sqlite3.Row
    return conn


def row_counts(conn: sqlite3.Connection) -> dict[str, int]:
    return {t: conn.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0] for t in SOURCE_TABLES}


def check_sqlite_integrity(conn: sqlite3.Connection) -> CheckResult:
    result = conn.execute("PRAGMA integrity_check").fetchone()[0]
    return CheckResult("sqlite_integrity_check", result == "ok", result)


def check_foreign_key_integrity(conn: sqlite3.Connection) -> CheckResult:
    violations = conn.execute("PRAGMA foreign_key_check").fetchall()
    return CheckResult(
        "sqlite_foreign_key_check", len(violations) == 0, f"{len(violations)} violation(s)"
    )


def check_duplicate_natural_keys(conn: sqlite3.Connection) -> list[CheckResult]:
    results = []

    def _dup(name: str, query: str) -> None:
        rows = conn.execute(query).fetchall()
        results.append(CheckResult(name, len(rows) == 0, f"{len(rows)} duplicate group(s)"))

    _dup("sources.code unique", "SELECT code, COUNT(*) c FROM sources GROUP BY code HAVING c > 1")
    _dup(
        "stories.(source_id,canonical_key) unique",
        "SELECT source_id, canonical_key, COUNT(*) c FROM stories "
        "GROUP BY source_id, canonical_key HAVING c > 1",
    )
    _dup(
        "illustration_units.(story_id,unit_index) unique",
        "SELECT story_id, unit_index, COUNT(*) c FROM illustration_units "
        "GROUP BY story_id, unit_index HAVING c > 1",
    )
    _dup(
        "tags.(category,slug) unique",
        "SELECT category, slug, COUNT(*) c FROM tags GROUP BY category, slug HAVING c > 1",
    )
    return results


def check_story_checksums(conn: sqlite3.Connection) -> CheckResult:
    rows = conn.execute(
        "SELECT id, original_text, original_text_checksum FROM stories "
        "WHERE original_text_checksum IS NOT NULL"
    ).fetchall()
    mismatches = [
        row["id"]
        for row in rows
        if hashlib.sha256(row["original_text"].encode("utf-8")).hexdigest()
        != row["original_text_checksum"]
    ]
    return CheckResult(
        "story original_text checksum verification",
        len(mismatches) == 0,
        f"{len(mismatches)} mismatch(es)" + (f": {mismatches[:10]}" if mismatches else ""),
    )


def check_tag_junction_integrity(conn: sqlite3.Connection) -> CheckResult:
    orphan_units = conn.execute(
        "SELECT COUNT(*) FROM illustration_unit_tags ut "
        "WHERE NOT EXISTS (SELECT 1 FROM illustration_units u WHERE u.id = ut.unit_id)"
    ).fetchone()[0]
    orphan_tags = conn.execute(
        "SELECT COUNT(*) FROM illustration_unit_tags ut "
        "WHERE NOT EXISTS (SELECT 1 FROM tags t WHERE t.id = ut.tag_id)"
    ).fetchone()[0]
    ok = orphan_units == 0 and orphan_tags == 0
    return CheckResult(
        "illustration_unit_tags junction integrity",
        ok,
        f"{orphan_units} orphan unit_id ref(s), {orphan_tags} orphan tag_id ref(s)",
    )


def check_enum_values(conn: sqlite3.Connection) -> list[CheckResult]:
    results = []

    def _enum(name: str, query: str, allowed: frozenset[str]) -> None:
        rows = conn.execute(query).fetchall()
        bad = [r[0] for r in rows if r[0] is not None and r[0] not in allowed]
        results.append(CheckResult(name, len(bad) == 0, f"unexpected: {bad[:10]}" if bad else ""))

    _enum("stories.status enum", "SELECT DISTINCT status FROM stories", ALLOWED_STORY_STATUSES)
    _enum(
        "stories.adaptation_status enum",
        "SELECT DISTINCT adaptation_status FROM stories",
        ALLOWED_ADAPTATION_STATUSES,
    )
    _enum(
        "illustration_units.status enum",
        "SELECT DISTINCT status FROM illustration_units",
        ALLOWED_UNIT_STATUSES,
    )
    _enum(
        "illustration_units.derivation_type enum",
        "SELECT DISTINCT derivation_type FROM illustration_units",
        ALLOWED_DERIVATION_TYPES,
    )
    _enum(
        "illustration_units.narrative_status enum",
        "SELECT DISTINCT narrative_status FROM illustration_units",
        ALLOWED_NARRATIVE_STATUSES,
    )
    _enum(
        "illustration_units.qa_status enum",
        "SELECT DISTINCT qa_status FROM illustration_units",
        ALLOWED_QA_STATUSES,
    )
    _enum("tags.category enum", "SELECT DISTINCT category FROM tags", ALLOWED_TAG_CATEGORIES)
    return results


def check_publish_state_invariants(conn: sqlite3.Connection) -> list[CheckResult]:
    results = []
    bad_content = conn.execute(
        "SELECT COUNT(*) FROM illustration_units WHERE status='published' AND "
        "(title_hu IS NULL OR modern_hu_text IS NULL OR summary_hu IS NULL OR human_reviewed_at IS NULL)"
    ).fetchone()[0]
    results.append(
        CheckResult(
            "published units have complete content + human_reviewed_at",
            bad_content == 0,
            f"{bad_content} violating row(s)",
        )
    )

    publishable_list = ",".join(f"'{s}'" for s in sorted(PUBLISHABLE_LICENSE_STATUSES))
    bad_license = conn.execute(
        f"""
        SELECT COUNT(*) FROM illustration_units u
        JOIN stories st ON st.id = u.story_id JOIN sources s ON s.id = st.source_id
        WHERE u.status = 'published' AND s.license_status NOT IN ({publishable_list})
        """
    ).fetchone()[0]
    results.append(
        CheckResult(
            "published units have publishable source license",
            bad_license == 0,
            f"{bad_license} violating row(s)",
        )
    )
    return results


def build_readiness_report(source_path: Path) -> MigrationReadinessReport:
    conn = open_source_readonly(source_path)
    try:
        checks = [check_sqlite_integrity(conn), check_foreign_key_integrity(conn)]
        checks.extend(check_duplicate_natural_keys(conn))
        checks.append(check_story_checksums(conn))
        checks.append(check_tag_junction_integrity(conn))
        checks.extend(check_enum_values(conn))
        checks.extend(check_publish_state_invariants(conn))
        return MigrationReadinessReport(
            source_path=source_path, row_counts=row_counts(conn), checks=checks
        )
    finally:
        conn.close()


# ---------------------------------------------------------------------------
# Row extraction (source SQLite -> plain dict rows, column names matching
# the Supabase DDL exactly -- see 20260913120000_illustration_corpus_
# layer.sql for the target shape each of these must match).
# ---------------------------------------------------------------------------


def extract_sources(conn: sqlite3.Connection) -> list[dict]:
    rows = conn.execute("SELECT * FROM sources").fetchall()
    return [
        {
            "id": r["id"], "code": r["code"], "title": r["title"], "author": r["author"],
            "orig_language": r["orig_language"], "publication_year": r["publication_year"],
            "edition_reference": r["edition_reference"], "license_status": r["license_status"],
            "license_basis_hu": r["license_basis_hu"], "rights_holder": r["rights_holder"],
            "source_url": r["source_url"], "retrieved_at": r["retrieved_at"],
            "reliability_tier": r["reliability_tier"], "notes_hu": r["notes_hu"],
            "tradition": r["tradition"], "registered_at": r["registered_at"],
        }
        for r in rows
    ]


def extract_stories(conn: sqlite3.Connection) -> list[dict]:
    rows = conn.execute("SELECT * FROM stories").fetchall()
    return [
        {
            "id": r["id"], "source_id": r["source_id"], "external_ref": r["external_ref"],
            "canonical_key": r["canonical_key"], "title_original": r["title_original"],
            "title_hu": r["title_hu"], "original_text": r["original_text"],
            "original_text_checksum": r["original_text_checksum"],
            "source_reference": r["source_reference"], "adaptation_status": r["adaptation_status"],
            "modern_hu_text": r["modern_hu_text"], "summary_hu": r["summary_hu"],
            "moral_hu": r["moral_hu"], "status": r["status"],
            "created_at": r["created_at"], "updated_at": r["updated_at"],
        }
        for r in rows
    ]


def extract_illustration_units(conn: sqlite3.Connection) -> list[dict]:
    import json

    rows = conn.execute("SELECT * FROM illustration_units").fetchall()
    out = []
    for r in rows:
        warnings = json.loads(r["enrichment_warnings_json"]) if r["enrichment_warnings_json"] else None
        issues = json.loads(r["qa_issues_json"]) if r["qa_issues_json"] else None
        out.append(
            {
                "id": r["id"], "story_id": r["story_id"], "unit_index": r["unit_index"],
                "derivation_type": r["derivation_type"],
                "source_span_start": r["source_span_start"], "source_span_end": r["source_span_end"],
                "title_hu": r["title_hu"], "modern_hu_text": r["modern_hu_text"],
                "summary_hu": r["summary_hu"], "moral_hu": r["moral_hu"],
                "narrative_status": r["narrative_status"],
                "narrative_status_confidence": r["narrative_status_confidence"],
                "status": r["status"], "enrichment_model": r["enrichment_model"],
                "enrichment_prompt_version": r["enrichment_prompt_version"],
                "enrichment_generated_at": r["enrichment_generated_at"],
                "enrichment_warnings": warnings,
                "qa_status": r["qa_status"], "qa_model": r["qa_model"],
                "qa_prompt_version": r["qa_prompt_version"], "qa_checked_at": r["qa_checked_at"],
                "qa_confidence": r["qa_confidence"], "qa_issues": issues,
                "human_reviewed_at": r["human_reviewed_at"],
                # reviewed_by (uuid) intentionally omitted -- no Supabase Auth
                # identity exists for any historical SQLite reviewer action;
                # reviewed_by_email also stays NULL for migrated rows (the
                # SQLite schema never recorded WHO reviewed a unit, only
                # WHEN -- see illustration_sqlite.py's human_reviewed_at
                # column, no reviewer-identity column exists there at all).
                "created_at": r["created_at"], "updated_at": r["updated_at"],
            }
        )
    return out


def extract_tags(conn: sqlite3.Connection) -> list[dict]:
    rows = conn.execute("SELECT * FROM tags").fetchall()
    return [{"id": r["id"], "category": r["category"], "slug": r["slug"], "label_hu": r["label_hu"]} for r in rows]


def extract_illustration_unit_tags(conn: sqlite3.Connection) -> list[dict]:
    rows = conn.execute("SELECT * FROM illustration_unit_tags").fetchall()
    return [{"unit_id": r["unit_id"], "tag_id": r["tag_id"]} for r in rows]


def extract_qa_repairs(conn: sqlite3.Connection) -> list[dict]:
    import json

    rows = conn.execute("SELECT * FROM qa_repairs").fetchall()
    return [
        {
            "id": r["id"], "unit_id": r["unit_id"], "repaired_at": r["repaired_at"],
            "qa_model": r["qa_model"], "qa_prompt_version": r["qa_prompt_version"],
            "issues_before": json.loads(r["issues_before_json"]),
            "fields_changed": json.loads(r["fields_changed_json"]),
            "before_values": json.loads(r["before_values_json"]),
            "after_values": json.loads(r["after_values_json"]),
        }
        for r in rows
    ]


def extract_import_meta(conn: sqlite3.Connection) -> list[dict]:
    rows = conn.execute("SELECT * FROM import_meta").fetchall()
    return [{"key": r["key"], "value": r["value"]} for r in rows]


def extract_enrichment_runs(conn: sqlite3.Connection) -> list[dict]:
    rows = conn.execute("SELECT * FROM enrichment_runs").fetchall()
    return [
        {
            "id": r["id"], "started_at": r["started_at"], "finished_at": r["finished_at"],
            "model_identifier": r["model_identifier"], "prompt_version": r["prompt_version"],
            "source_code": r["source_code"], "strategy_band": r["strategy_band"],
            "requested_limit": r["requested_limit"], "overall_status": r["overall_status"],
            "selection_metadata": r["selection_metadata_json"],
        }
        for r in rows
    ]


def extract_enrichment_run_items(conn: sqlite3.Connection) -> list[dict]:
    rows = conn.execute("SELECT * FROM enrichment_run_items").fetchall()
    return [
        {
            "id": r["id"], "run_id": r["run_id"], "story_id": r["story_id"],
            "expected_mode": r["expected_mode"], "status": r["status"],
            "illustration_unit_id": r["illustration_unit_id"], "error_message": r["error_message"],
            "warnings": r["warnings_json"], "started_at": r["started_at"], "finished_at": r["finished_at"],
        }
        for r in rows
    ]


# ---------------------------------------------------------------------------
# Chunked idempotent upsert with bounded retry -- matches the established
# scripts/import_greek_syntax_to_supabase.py pattern (PostgREST client,
# batched, retried with exponential backoff), NOT a single wrapping DB
# transaction -- see the Phase 1 report §8 for why that pattern was
# chosen over a raw psycopg2 connection or a single migration RPC.
# ---------------------------------------------------------------------------


def _chunks(items: list, size: int):
    for i in range(0, len(items), size):
        yield items[i : i + size]


def _with_retry(fn, *, attempts: int = DEFAULT_RETRY_ATTEMPTS, base_delay: float = DEFAULT_RETRY_BASE_DELAY, description: str = ""):
    last_exc: Exception | None = None
    for attempt in range(attempts):
        try:
            return fn()
        except Exception as exc:  # noqa: BLE001 -- retried broadly, re-raised if exhausted
            last_exc = exc
            if attempt == attempts - 1:
                raise
            delay = base_delay * (2**attempt)
            print(f"  retry {attempt + 1}/{attempts} after error ({description}): {exc} -- sleeping {delay:.1f}s")
            time.sleep(delay)
    raise last_exc  # pragma: no cover -- unreachable, loop always returns or raises


class SupabaseMigrationWriter:
    """Thin wrapper over a `supabase.Client` -- upsert-only, chunked,
    retried. Never issues a DELETE against anything. `on_conflict` names
    each table's natural unique constraint, matching the DDL exactly."""

    def __init__(self, client, *, batch_size: int = DEFAULT_BATCH_SIZE) -> None:
        self.client = client
        self.batch_size = batch_size

    def upsert(self, table: str, rows: list[dict], *, on_conflict: str) -> int:
        written = 0
        for chunk in _chunks(rows, self.batch_size):
            _with_retry(
                lambda chunk=chunk: self.client.table(table).upsert(chunk, on_conflict=on_conflict).execute(),
                description=f"upsert {table} ({len(chunk)} rows)",
            )
            written += len(chunk)
            print(f"  upserted {len(chunk)} row(s) into {table} (running total: {written}/{len(rows)})")
        return written

    def reset_sequences(self) -> None:
        _with_retry(
            lambda: self.client.rpc("reset_illustration_sequences", {}).execute(),
            description="reset_illustration_sequences RPC",
        )
        print("  sequences reset to MAX(id)+1 for all identity-PK tables")


NATURAL_KEYS = {
    "illustration_sources": "code",
    "illustration_stories": "source_id,canonical_key",
    "illustration_units": "story_id,unit_index",
    "illustration_tags": "category,slug",
    "illustration_unit_tags": "unit_id,tag_id",
    "illustration_qa_repairs": "id",  # no natural key beyond the migrated SQLite id itself
    "illustration_import_meta": "key",
    "illustration_enrichment_runs": "id",
    "illustration_enrichment_run_items": "run_id,story_id",
}


def run_migration(source_path: Path, *, apply: bool, supabase_client=None, batch_size: int = DEFAULT_BATCH_SIZE) -> int:
    report = build_readiness_report(source_path)
    print(report.render())

    if not apply:
        print("\n--dry-run (default) -- no Supabase write attempted. Pass --apply to write.")
        return 0 if report.ready_for_apply else 1

    if not report.ready_for_apply:
        print("\nABORTED: readiness checks failed -- refusing to --apply. Fix the FAIL items above first.")
        return 1

    conn = open_source_readonly(source_path)
    try:
        payloads = {
            "illustration_sources": extract_sources(conn),
            "illustration_stories": extract_stories(conn),
            "illustration_units": extract_illustration_units(conn),
            "illustration_tags": extract_tags(conn),
            "illustration_unit_tags": extract_illustration_unit_tags(conn),
            "illustration_qa_repairs": extract_qa_repairs(conn),
            "illustration_import_meta": extract_import_meta(conn),
            "illustration_enrichment_runs": extract_enrichment_runs(conn),
            "illustration_enrichment_run_items": extract_enrichment_run_items(conn),
        }
    finally:
        conn.close()

    if supabase_client is None:
        # 2026-09-13 production incident fix: this MUST be the service_role
        # client, never supabase_client.get_supabase_client() (the anon/
        # publishable client every other read path in this repo uses) --
        # illustration_* tables have zero anon/authenticated grants by
        # design (see the DDL migration's RLS section), so an anon-tier
        # client's first INSERT is correctly rejected by Postgres with
        # "permission denied for table ...". Reuses the project's one
        # existing service-role credential loader rather than duplicating
        # its URL/key resolution here -- see that module's docstring for
        # why this is a DIFFERENT function from the reviewer-gated one.
        from illustration_engine.supabase_review_client import get_service_role_client_for_migration

        supabase_client = get_service_role_client_for_migration()

    writer = SupabaseMigrationWriter(supabase_client, batch_size=batch_size)
    print("\n=== Applying migration ===")
    for table, rows in payloads.items():
        print(f"\n{table}: {len(rows)} row(s)")
        writer.upsert(table, rows, on_conflict=NATURAL_KEYS[table])

    print("\nResetting identity sequences...")
    writer.reset_sequences()

    print("\nMigration apply complete. Run the migration's own post-apply verification "
          "(row-count + spot-check comparison against the source) before treating Supabase "
          "as authoritative.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, required=True, help="Path to the source illustrations.sqlite3 (opened read-only).")
    parser.add_argument("--apply", action="store_true", help="Actually write to Supabase. Without this flag, runs in --dry-run mode.")
    parser.add_argument("--batch-size", type=int, default=DEFAULT_BATCH_SIZE)
    args = parser.parse_args()

    return run_migration(args.source, apply=args.apply, batch_size=args.batch_size)


if __name__ == "__main__":
    sys.exit(main())
