-- Illustration corpus — persistent Supabase source of truth (Phase 1).
--
-- Ports the local SQLite illustration engine (illustration_engine/
-- illustration_sqlite.py, schema v6) to Supabase, preserving the exact
-- workflow semantics (draft -> needs_review -> approved -> published),
-- the exact fail-closed gates (content-completeness CHECK, license
-- trigger, human-review-protection trigger), and every original SQLite
-- integer id (see the PK note below) -- NOT a redesign, a faithful port.
--
-- Context (2026-09 provenance audit): the SQLite file this was ported
-- from is gitignored, was never present in any production deployment,
-- and lives in a single stray development worktree with no backup or
-- persistence guarantee. Supabase becomes the durable source of truth;
-- the SQLite backend remains available for local development only (see
-- TEXTUS_ILLUSTRATION_BACKEND in illustration_engine/backend_config.py).
--
-- This migration has been validated locally (structurally reviewed
-- against the SQLite schema it ports, and exercised by
-- tests/test_illustration_supabase_ddl_shape.py) but has NOT been
-- applied to any real Supabase project yet -- same "written, reviewed,
-- not yet applied" convention as every other migration in this
-- directory (see e.g. 20260908190000's header note).
--
-- ===========================================================================
-- PRIMARY KEY STRATEGY
-- ===========================================================================
-- Every table uses `bigint generated BY DEFAULT as identity` (not
-- `ALWAYS`) specifically so the one-time migration script
-- (scripts/migrate_illustrations_to_supabase.py) can INSERT the
-- ORIGINAL SQLite integer ids explicitly -- every foreign key
-- (source_id, story_id, unit_id, tag_id) carries over verbatim, with NO
-- id-remapping table needed anywhere in the migration script. After the
-- one-time migration, the script resets each table's identity sequence
-- to MAX(id)+1 (via pg_get_serial_sequence + setval) so ordinary new
-- rows created afterward get correct, non-colliding ids automatically.
--
-- ===========================================================================
-- AUTH MODEL — SERVER-TRUST, NOT RLS USER-AUTH (read this before adding
-- any write path against these tables)
-- ===========================================================================
-- Textus's Google login goes through Streamlit's native `st.login()` +
-- Google OIDC (see .streamlit/secrets.toml.example) -- it does NOT
-- establish a Supabase Auth session, so `auth.uid()` is NOT populated
-- for a logged-in Textus reviewer today. Building RLS policies or
-- SECURITY DEFINER RPCs that trust a client-supplied identity (an email
-- parameter, a header, anything the caller controls) would be trivially
-- forgeable -- an email string alone proves nothing.
--
-- The write path (approve/publish/send-back/tag-replace) is therefore
-- NOT modeled as RLS user-auth in this migration. It is a SERVER-TRUST
-- model instead:
--   1. `illustration_review_ui.is_authorized_reviewer()` (Streamlit-side,
--      unchanged) is the ONLY authorization check -- strict loopback
--      host OR an authenticated Google session matching the hardcoded
--      owner email.
--   2. ONLY after that check passes does the server-side Python code
--      obtain a Supabase `service_role` client (see
--      illustration_engine/supabase_review_client.py, Phase 1 skeleton
--      below) -- via a gated factory function, never a bare
--      `get_supabase_client()` call reachable from anywhere else.
--   3. `service_role` bypasses RLS by Postgres/Supabase design -- so RLS
--      policies on these tables are NOT the write-path's security
--      boundary. The security boundary is: (a) the service_role key
--      lives ONLY in Streamlit Secrets/env, never sent to a browser --
--      trivially true here, since Streamlit renders server-side and has
--      no client-side JS calling Supabase directly; (b) the gated
--      factory function is the ONLY place in the codebase allowed to
--      construct that client; (c) every CHECK constraint and trigger in
--      this file still fully applies to a service_role write --
--      service_role bypasses RLS, NOT constraints/triggers, so the data-
--      integrity gates (content-completeness, license, human-review
--      protection, tag protection) hold regardless of which key wrote
--      the row.
--   4. `reviewed_by_email` is populated from the ALREADY-authenticated
--      Streamlit Google session (the same identity `is_authorized_
--      reviewer()` just checked), never from a request/form parameter.
--   5. `reviewed_by uuid` stays nullable -- populated only once a real
--      Supabase Auth session is bridged for the reviewer (a documented,
--      NOT-YET-BUILT follow-up; see the Phase 1 report). Until then it
--      is always NULL and `reviewed_by_email` is the only reviewer
--      identity actually recorded.
--
-- RLS is still enabled with NO policies on every table below (deny-by-
-- default for anon/authenticated) -- this is defense in depth against a
-- future, different write path ever being added carelessly, not the
-- mechanism the CURRENT write path relies on.
--
-- The ONE read path this migration exposes to `anon`/`authenticated` is
-- the narrow, SECURITY DEFINER `get_published_illustration_candidates()`
-- RPC (bottom of this file) -- genuinely public-safe: it independently
-- re-checks status='published' AND source license publishable on every
-- call, and returns only the fields retrieval actually needs (never
-- qa_issues, enrichment audit fields, or reviewer metadata).

-- ===========================================================================
-- 1. sources
-- ===========================================================================

create table if not exists illustration_sources (
    id bigint generated by default as identity primary key,
    code text not null unique,
    title text not null,
    author text,
    orig_language text not null,
    publication_year integer,
    edition_reference text,
    license_status text not null check (license_status in (
        'public_domain_confirmed', 'public_domain_assumed_by_age',
        'permission_granted', 'unknown', 'restricted'
    )),
    license_basis_hu text not null,
    rights_holder text,
    source_url text,
    retrieved_at timestamptz,
    reliability_tier text not null,
    notes_hu text,
    tradition text,
    registered_at timestamptz not null default now()
);

-- ===========================================================================
-- 2. stories (immutable raw provenance layer -- mirrors SQLite exactly)
-- ===========================================================================

create table if not exists illustration_stories (
    id bigint generated by default as identity primary key,
    source_id bigint not null references illustration_sources(id),
    external_ref text not null,
    canonical_key text not null,
    title_original text not null,
    title_hu text,
    original_text text,
    original_text_checksum text,
    source_reference text,
    adaptation_status text not null check (adaptation_status in (
        'verbatim_transcription', 'modernized_spelling', 'editorial_paraphrase'
    )),
    modern_hu_text text,
    summary_hu text,
    moral_hu text,
    status text not null default 'draft' check (status in ('draft','needs_review','approved','published')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (source_id, canonical_key),
    check (
        status != 'published'
        or (title_hu is not null and modern_hu_text is not null and summary_hu is not null)
    )
);

create index if not exists idx_illustration_stories_source on illustration_stories(source_id);
create index if not exists idx_illustration_stories_status on illustration_stories(status);

create or replace function trg_illustration_stories_set_updated_at() returns trigger as $$
begin
    new.updated_at := now();
    return new;
end;
$$ language plpgsql;

create trigger illustration_stories_set_updated_at
    before update on illustration_stories
    for each row execute function trg_illustration_stories_set_updated_at();

-- SQL-layer license gate for stories -- mirrors
-- trg_stories_publish_requires_license_{insert,update} in illustration_sqlite.py.
create or replace function trg_illustration_stories_publish_license_gate() returns trigger as $$
begin
    if new.status = 'published' and not exists (
        select 1 from illustration_sources s
        where s.id = new.source_id
          and s.license_status in ('public_domain_confirmed','public_domain_assumed_by_age','permission_granted')
    ) then
        raise exception 'license_gate: source license_status does not permit published status (story id=%)', new.id;
    end if;
    return new;
end;
$$ language plpgsql;

create trigger illustration_stories_publish_license_gate
    before insert or update of status, source_id on illustration_stories
    for each row execute function trg_illustration_stories_publish_license_gate();

-- ===========================================================================
-- 3. illustration_units — the primary retrieval object
-- ===========================================================================

create table if not exists illustration_units (
    id bigint generated by default as identity primary key,
    story_id bigint not null references illustration_stories(id),
    unit_index integer not null,
    derivation_type text not null check (derivation_type in
        ('full_story_translation','condensed_story','extracted_scene')),
    source_span_start integer,
    source_span_end integer,
    title_hu text,
    modern_hu_text text,
    summary_hu text,
    moral_hu text,
    narrative_status text check (narrative_status is null or narrative_status in (
        'documented_historical_event','legend_about_historical_figure','traditional_anecdote',
        'fable','folktale','rabbinic_aggadic_tale','didactic_tale'
    )),
    narrative_status_confidence text check (
        narrative_status_confidence is null or narrative_status_confidence in ('low','medium','high')
    ),
    status text not null default 'draft' check (status in ('draft','needs_review','approved','published')),
    enrichment_model text,
    enrichment_prompt_version text,
    enrichment_generated_at timestamptz,
    enrichment_warnings jsonb,
    qa_status text check (qa_status is null or qa_status in ('pending','passed','needs_attention','failed')),
    qa_model text,
    qa_prompt_version text,
    qa_checked_at timestamptz,
    qa_confidence real,
    qa_issues jsonb,
    -- REVIEW METADATA -- server-trust model, see the header note above.
    human_reviewed_at timestamptz,
    reviewed_by uuid references auth.users(id),          -- nullable until a real Supabase Auth bridge exists
    reviewed_by_email text,                                -- populated from the authenticated Streamlit session
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (story_id, unit_index),
    check (
        status != 'published'
        or (
            title_hu is not null and modern_hu_text is not null and summary_hu is not null
            and human_reviewed_at is not null
        )
    ),
    check ((source_span_start is null) = (source_span_end is null)),
    check (source_span_end is null or source_span_end > source_span_start),
    check (
        derivation_type != 'extracted_scene'
        or (source_span_start is not null and source_span_end is not null)
    ),
    check ((narrative_status is null) = (narrative_status_confidence is null))
);

create index if not exists idx_illustration_units_story on illustration_units(story_id);
create index if not exists idx_illustration_units_status on illustration_units(status);
-- Retrieval-shape index: the production RPC always filters on exactly
-- this pair together.
create index if not exists idx_illustration_units_status_story on illustration_units(status, story_id);

-- SQL-layer license gate -- mirrors trg_units_publish_requires_license_*.
create or replace function trg_illustration_units_publish_license_gate() returns trigger as $$
begin
    if new.status = 'published' and not exists (
        select 1
        from illustration_stories st join illustration_sources s on s.id = st.source_id
        where st.id = new.story_id
          and s.license_status in ('public_domain_confirmed','public_domain_assumed_by_age','permission_granted')
    ) then
        raise exception 'license_gate: source license_status does not permit published status (unit id=%)', new.id;
    end if;
    return new;
end;
$$ language plpgsql;

create trigger illustration_units_publish_license_gate
    before insert or update of status, story_id on illustration_units
    for each row execute function trg_illustration_units_publish_license_gate();

-- Human-review-protection trigger — mirrors
-- trg_units_protect_human_reviewed_content exactly (same field list, same
-- "clearing human_reviewed_at alone is not enough, status must also drop
-- to needs_review in the SAME write" rule), also bumps updated_at.
create or replace function trg_illustration_units_protect_reviewed_content() returns trigger as $$
begin
    if old.human_reviewed_at is not null
       and (
            new.title_hu is distinct from old.title_hu
            or new.modern_hu_text is distinct from old.modern_hu_text
            or new.summary_hu is distinct from old.summary_hu
            or new.moral_hu is distinct from old.moral_hu
            or new.narrative_status is distinct from old.narrative_status
            or new.enrichment_model is distinct from old.enrichment_model
            or new.enrichment_prompt_version is distinct from old.enrichment_prompt_version
            or new.enrichment_generated_at is distinct from old.enrichment_generated_at
            or new.enrichment_warnings is distinct from old.enrichment_warnings
       )
       and not (new.human_reviewed_at is null and new.status = 'needs_review')
    then
        raise exception 'review_gate: reviewed content can only change together with human_reviewed_at cleared AND status reset to needs_review (unit id=%)', new.id;
    end if;
    new.updated_at := now();
    return new;
end;
$$ language plpgsql;

create trigger illustration_units_protect_reviewed_content
    before update on illustration_units
    for each row execute function trg_illustration_units_protect_reviewed_content();

-- ===========================================================================
-- 4. tags + junction (taxonomy)
-- ===========================================================================

create table if not exists illustration_tags (
    id bigint generated by default as identity primary key,
    category text not null check (category in ('topic','tone','function')),
    slug text not null,
    label_hu text not null,
    unique (category, slug)
);

create table if not exists illustration_unit_tags (
    unit_id bigint not null references illustration_units(id) on delete cascade,
    tag_id bigint not null references illustration_tags(id),
    primary key (unit_id, tag_id)
);

create index if not exists idx_illustration_unit_tags_unit on illustration_unit_tags(unit_id);
create index if not exists idx_illustration_unit_tags_tag on illustration_unit_tags(tag_id);

-- Taxonomy review-protection trigger (audit fix ported from the SQLite
-- side, see illustration_engine/illustration_unit_repository.py's
-- replace_review_tags() docstring -- "REVIEW PROTECTION (audit fix,
-- 2026-09-13)"): a unit's tags are content, exactly like title_hu, and
-- must be equally protected once human_reviewed_at is set. Blocks BOTH
-- insert (adding a tag) and delete (removing a tag) on an already-
-- reviewed unit -- the caller must demote the unit (clear
-- human_reviewed_at, reset status to needs_review) first. This is the
-- DB-layer half of the guarantee; the Python-side service-role review
-- repository (Phase 1 skeleton) enforces the identical rule before ever
-- issuing the write, for a clearer error message -- same "Python check
-- for UX, DB trigger for the actual fail-closed guarantee" split as
-- every other gate in this schema.
create or replace function trg_illustration_unit_tags_protect_reviewed() returns trigger as $$
declare
    v_unit_id bigint := coalesce(new.unit_id, old.unit_id);
    v_human_reviewed_at timestamptz;
begin
    select human_reviewed_at into v_human_reviewed_at
    from illustration_units where id = v_unit_id;

    if v_human_reviewed_at is not null then
        raise exception 'review_gate: unit % taxonomy is protected (human_reviewed_at=%) -- call send_back_for_rework first', v_unit_id, v_human_reviewed_at;
    end if;
    return coalesce(new, old);
end;
$$ language plpgsql;

create trigger illustration_unit_tags_protect_reviewed
    before insert or delete on illustration_unit_tags
    for each row execute function trg_illustration_unit_tags_protect_reviewed();

-- ===========================================================================
-- 5. qa_repairs (audit trail, also read by the review UI)
-- ===========================================================================

create table if not exists illustration_qa_repairs (
    id bigint generated by default as identity primary key,
    unit_id bigint not null references illustration_units(id),
    repaired_at timestamptz not null default now(),
    qa_model text not null,
    qa_prompt_version text not null,
    issues_before jsonb not null,
    fields_changed jsonb not null,
    before_values jsonb not null,
    after_values jsonb not null
);

create index if not exists idx_illustration_qa_repairs_unit on illustration_qa_repairs(unit_id);

-- ===========================================================================
-- 6. import_meta / enrichment_runs / enrichment_run_items — provenance,
--    migrated per the revised plan (previously deferred, now brought in).
-- ===========================================================================

create table if not exists illustration_import_meta (
    key text primary key,
    value text not null
);

create table if not exists illustration_enrichment_runs (
    id bigint generated by default as identity primary key,
    started_at timestamptz not null,
    finished_at timestamptz,
    model_identifier text not null,
    prompt_version text not null,
    source_code text,
    strategy_band text check (strategy_band is null or strategy_band in ('A','B','C')),
    requested_limit integer,
    overall_status text not null default 'created' check (
        overall_status in ('created','running','completed','completed_with_errors','interrupted')
    ),
    selection_metadata jsonb
);

create table if not exists illustration_enrichment_run_items (
    id bigint generated by default as identity primary key,
    run_id bigint not null references illustration_enrichment_runs(id),
    story_id bigint not null references illustration_stories(id),
    expected_mode text not null check (expected_mode in ('direct_unit','unit_proposal')),
    status text not null default 'pending' check (
        status in ('pending','running','success','warning','rejected','proposal_ready','failed')
    ),
    illustration_unit_id bigint references illustration_units(id),
    error_message text,
    warnings jsonb,
    started_at timestamptz,
    finished_at timestamptz,
    unique (run_id, story_id)
);

create index if not exists idx_illustration_enrichment_run_items_run on illustration_enrichment_run_items(run_id);
create index if not exists idx_illustration_enrichment_run_items_run_status
    on illustration_enrichment_run_items(run_id, status);

-- Deliberately NOT migrated (see the Phase-1 report for the full audit):
--   story_tags        -- 0 rows in the source SQLite DB, no code path reads or writes it.
--   illustration_units_fts (SQLite FTS5) -- not used by the live retrieval
--                         pipeline (find_candidates scores the full eligible
--                         pool in Python, see illustration_engine/retrieval.py);
--                         a Postgres-native full-text solution (pg_trgm /
--                         tsvector) would need separate design if the
--                         currently-unused illustration_unit_repository.
--                         search_units() helper is ever wired into a UI.

-- ===========================================================================
-- Row Level Security — deny-by-default on every table. See the header
-- note: this is defense in depth, NOT the write path's actual security
-- boundary (the write path is server-trust via a gated service_role
-- client). No policies are defined for anon/authenticated on any of
-- these tables -- every read a public user needs goes through the one
-- narrow RPC below instead.
-- ===========================================================================

-- 2026-09-13 real-PostgreSQL validation finding: service_role does NOT
-- automatically receive base table privileges just by existing -- the
-- established convention in this repo's OWN prior migrations
-- (20260908190000_hebrew_linguistic_layer.sql, 20260911220000_greek_
-- linguistic_layer.sql) EXPLICITLY grants select/insert/update/delete to
-- service_role per table, rather than assuming a platform default. This
-- migration initially omitted that explicit grant (an oversight caught by
-- a local disposable-Postgres validation run, NOT assumed from Supabase's
-- behavior) -- without it, the review write path's service_role client
-- would get "permission denied for table ..." on every write, in a real
-- project exactly as it did in this local test. Fixed to match the
-- established pattern exactly.
do $$
declare
    tbl text;
begin
    for tbl in
        select unnest(array[
            'illustration_sources',
            'illustration_stories',
            'illustration_units',
            'illustration_tags',
            'illustration_unit_tags',
            'illustration_qa_repairs',
            'illustration_import_meta',
            'illustration_enrichment_runs',
            'illustration_enrichment_run_items'
        ])
    loop
        execute format('alter table %I enable row level security;', tbl);
        execute format('revoke all on %I from anon, authenticated;', tbl);
        execute format('grant select, insert, update, delete on %I to service_role;', tbl);
    end loop;
end;
$$;

-- ===========================================================================
-- Production read RPC — the ONLY surface anon/authenticated ever touches.
-- ===========================================================================
--
-- SECURITY DEFINER is required here (unlike the service_role-only Hebrew
-- bundle RPC above, which never needs it because service_role already
-- bypasses RLS regardless of invoker/definer): anon/authenticated hold
-- NO table grants and NO RLS policies on these tables, so a plain
-- (default SECURITY INVOKER) function called by anon would see zero
-- rows. SECURITY DEFINER runs with the function owner's privileges
-- instead, but the function body itself is the only thing that decides
-- what is exposed -- and it re-derives the exact same filter
-- illustration_engine.illustration_sqlite's published_illustration_units
-- SQLite view already enforces (status='published' AND source license
-- publishable), on every single call, never trusting the publish-time
-- trigger alone (Textus architecture decision, 2026-09-13: a source
-- retroactively marked 'restricted' must immediately stop surfacing its
-- previously-published units). `set search_path = public` is required
-- security hygiene for any SECURITY DEFINER function (prevents a
-- search_path-hijack attack).
--
-- Field list is deliberately narrow: title_hu/modern_hu_text/summary_hu/
-- moral_hu/topics/tone/homiletic_functions/source_title/source_code/
-- tradition/license_status -- retrieval.py's RetrievalCandidate shape,
-- nothing more. NEVER qa_issues, qa_confidence, enrichment_model,
-- enrichment_warnings, reviewed_by, reviewed_by_email, or any other
-- admin/reviewer-facing field.
create or replace function get_published_illustration_candidates()
returns table (
    unit_id bigint,
    title_hu text,
    modern_hu_text text,
    summary_hu text,
    moral_hu text,
    topics text[],
    tone text,
    homiletic_functions text[],
    source_title text,
    source_code text,
    tradition text,
    license_status text,
    original_text text,
    original_text_checksum text
)
language sql
stable
security definer
set search_path = public
as $$
    select
        u.id as unit_id,
        u.title_hu,
        u.modern_hu_text,
        u.summary_hu,
        u.moral_hu,
        coalesce(
            (select array_agg(t.slug order by t.slug) from illustration_unit_tags ut
             join illustration_tags t on t.id = ut.tag_id
             where ut.unit_id = u.id and t.category = 'topic'),
            '{}'::text[]
        ) as topics,
        (select t.slug from illustration_unit_tags ut
         join illustration_tags t on t.id = ut.tag_id
         where ut.unit_id = u.id and t.category = 'tone' limit 1) as tone,
        coalesce(
            (select array_agg(t.slug order by t.slug) from illustration_unit_tags ut
             join illustration_tags t on t.id = ut.tag_id
             where ut.unit_id = u.id and t.category = 'function'),
            '{}'::text[]
        ) as homiletic_functions,
        s.title as source_title,
        s.code as source_code,
        s.tradition,
        s.license_status,
        st.original_text,
        st.original_text_checksum
    from illustration_units u
    join illustration_stories st on st.id = u.story_id
    join illustration_sources s on s.id = st.source_id
    where u.status = 'published'
      and s.license_status in ('public_domain_confirmed','public_domain_assumed_by_age','permission_granted');
$$;

revoke all on function get_published_illustration_candidates() from public;
grant execute on function get_published_illustration_candidates() to anon, authenticated;

comment on function get_published_illustration_candidates() is
    'Read-only, SECURITY DEFINER. Re-checks status=published AND source license publishable on every call, independent of the publish-time trigger. Returns only retrieval-relevant fields -- never qa_issues, enrichment provenance, or reviewer identity. Safe for the anon key.';

-- ===========================================================================
-- Post-migration sequence reset — used ONCE by
-- scripts/migrate_illustrations_to_supabase.py's --apply path, after all
-- explicit-id rows have been inserted (see the PRIMARY KEY STRATEGY note
-- at the top of this file). service_role-only: this is an administrative
-- migration operation, never called from the live app.
create or replace function reset_illustration_sequences()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    t record;
begin
    for t in
        select unnest(array[
            'illustration_sources', 'illustration_stories', 'illustration_units',
            'illustration_tags', 'illustration_qa_repairs',
            'illustration_enrichment_runs', 'illustration_enrichment_run_items'
        ]) as table_name
    loop
        execute format(
            'select setval(pg_get_serial_sequence(%L, ''id''), coalesce((select max(id) from %I), 1), (select max(id) from %I) is not null)',
            t.table_name, t.table_name, t.table_name
        );
    end loop;
end;
$$;

revoke all on function reset_illustration_sequences() from public, anon, authenticated;
grant execute on function reset_illustration_sequences() to service_role;

comment on function reset_illustration_sequences() is
    'One-time post-migration step: resets every identity sequence to MAX(id) so ordinary new rows created after the bulk explicit-id migration get correct, non-colliding ids. service_role-only, called exactly once by scripts/migrate_illustrations_to_supabase.py --apply.';
