-- Illustration story processing outcomes (minimal REJECT/processed registry).
--
-- CONTEXT: production currently only distinguishes "a story has an
-- illustration_unit" from "it doesn't" -- there is no persistent record of
-- a story that an enrichment batch already looked at and explicitly
-- REJECTed (duplicate, unusable, out of scope, etc). Future batches select
-- purely from illustration_stories/illustration_units, so a previously
-- REJECTed story is indistinguishable from a never-attempted one and can be
-- re-selected, re-classified, and re-REJECTed by a later batch -- wasted
-- work with no benefit.
--
-- LESS-INVASIVE-OPTION ANALYSIS (both options were considered, per the
-- 2026-09-15 maintenance-round request): extending illustration_stories.status
-- (draft/needs_review/approved/published, see 20260913120000) with a 5th
-- value would (a) require altering an existing CHECK constraint on a table
-- with 1000+ live rows already governed by a publish-completeness CHECK and
-- two triggers, and (b) conflate two different concepts -- "status" is the
-- raw-provenance/curation lifecycle, not "an enrichment batch attempted and
-- rejected this." A brand-new, purely additive table has zero interaction
-- with any existing constraint, trigger, or row and can be ignored/dropped
-- without touching illustration_stories or illustration_units at all --
-- this is the smaller, cleaner, less invasive change, so that's what this
-- migration does.
--
-- One row per story: the story's current, latest-known processing outcome
-- (not a full history log -- future rescues upsert the same row via
-- ON CONFLICT (story_id) DO UPDATE). `reason` is intentionally short
-- (<=200 chars) -- a REJECT category, not the LLM's full reasoning.
--
-- Same "written, reviewed, applied out-of-band via the Supabase SQL Editor"
-- convention as every other migration in this directory (the Supabase
-- Python/PostgREST client used by this repo's scripts cannot execute DDL --
-- see scripts/setup_hebrew_linguistic_schema.py's header).

create table if not exists illustration_story_outcomes (
    id bigint generated by default as identity primary key,
    story_id bigint not null references illustration_stories(id),
    outcome text not null check (outcome in ('unit_created', 'rejected')),
    processor text not null,
    reason text check (reason is null or char_length(reason) <= 200),
    processed_at timestamptz not null default now(),
    unique (story_id)
);

create index if not exists idx_illustration_story_outcomes_outcome
    on illustration_story_outcomes(outcome);

comment on table illustration_story_outcomes is
    'Persistent, minimal registry of what happened when an enrichment batch looked at a raw story: outcome=unit_created (a unit now exists -- also independently derivable from illustration_units.story_id, kept here for a single queryable audit trail) or outcome=rejected (explicitly rejected by a batch and no unit exists). One row per story_id (latest outcome, upserted on rescue). Future batch selection should skip any story_id present here with outcome=rejected in addition to skipping any story_id that already has an illustration_unit.';
comment on column illustration_story_outcomes.processor is
    'Identifier of the batch/workflow that produced this outcome, e.g. claude_enrichment_batch_v8_c1 -- mirrors illustration_units.auto_approval_rule_version naming.';
comment on column illustration_story_outcomes.reason is
    'Short REJECT category only (e.g. "duplicate_of_story_707", "unusable_short_fragment") -- never a long LLM justification.';

-- ===========================================================================
-- Reference query for future enrichment-batch selection
-- ===========================================================================
-- Not wired into any executable selection script by this migration -- no
-- new batch is started in this maintenance round. The next batch's
-- selection step should use exactly this shape (production remains the
-- sole source of truth): a story is eligible only if it has no unit yet
-- AND no persistent 'rejected' outcome recorded here.
--
--   select s.id
--   from illustration_stories s
--   where not exists (select 1 from illustration_units u where u.story_id = s.id)
--     and not exists (
--       select 1 from illustration_story_outcomes o
--       where o.story_id = s.id and o.outcome = 'rejected'
--     )
--   order by s.source_id, s.id;
